## Customize the test machine
machine:

  timezone:
    UTC # Set the timezone to UTC

  hosts: # specified the api.datalanche.com server
    api.datalanche.com: 50.19.4.47

  # Version of nodejs to use
  node:
    version: 0.10.23

## Customize test commands
test:
  override:
    # run the auto_exam bash script to test examples automatically
    - bash -c "cd test/; make"