#!/bin/bash
#host localhost

echo
echo create a new table with the name of my_table
node ../local_examples/table/create_table.js

echo
echo insert data into my_table
node ../local_examples/table/insert.js

echo rename the table my_table to t1
# make sure the previous alterred schemas are cleaned up before examples testing
curl https://localhost:4001/my_database/query -X POST -k -u "xeeFjAIlQMi/E+q4uFe1Rg==:6X3eolu/QFyds2BpJdMONg==" -H "Content-Type: application/json" -d '{
                        "alter_table": "my_schema.my_table",
			                  "rename_to": "t1"
                      }'

echo
echo create a new table with the name of my_table
node ../local_examples/table/create_table.js

echo
echo insert data into my_table
node ../local_examples/table/insert.js

echo rename the table my_table to t2
# make sure the previous alterred schemas are cleaned up before examples testing
curl https://localhost:4001/my_database/query -X POST -k -u "xeeFjAIlQMi/E+q4uFe1Rg==:6X3eolu/QFyds2BpJdMONg==" -H "Content-Type: application/json" -d '{
                        "alter_table": "my_schema.my_table",
			                  "rename_to": "t2"
                      }'

echo
echo create a new table with the name of my_table
node ../local_examples/table/create_table.js

echo
echo insert data into my_table
node ../local_examples/table/insert.js

echo
echo rename the table my_table to t3
# make sure the previous alterred schemas are cleaned up before examples testing
curl https://localhost:4001/my_database/query -X POST -k -u "xeeFjAIlQMi/E+q4uFe1Rg==:6X3eolu/QFyds2BpJdMONg==" -H "Content-Type: application/json" -d '{
                        "alter_table": "my_schema.my_table",
			                  "rename_to": "t3"
                      }'

echo
echo create a new schema named my_new_schema
curl https://localhost:4001/my_database/query -X POST -k -u "xeeFjAIlQMi/E+q4uFe1Rg==:6X3eolu/QFyds2BpJdMONg==" -H "Content-Type: application/json" -H "Content-Type: application/json" -d '{
                                "create_schema": "my_new_schema",
                                "description": "An optional description of my_new_schema."
                              }'


echo
echo create a new table with the name of my_table
node ../local_examples/table/create_table.js

echo
echo insert data into my_table
node ../local_examples/table/insert.js